version: '3.9'

services:
  postgresdb:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    networks:
      - app_network
    restart: unless-stopped
    ports:
      - "15432:5432"
    volumes:
      - db:/var/lib/postgres/data

  app:
    image: app:latest
    networks:
      - app_network
    restart: always
    container_name: app
    depends_on:
      - postgresdb
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx_webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db: