version: '3.9'

services:
  postgresdb:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - app_network
    restart: unless-stopped
    ports:
      - "15432:5432"
    volumes:
      - db:/var/lib/postgres/data

  app:
    networks:
      - app_network
    restart: always
    container_name: app
    depends_on:
      - db
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123
  nginx:
    image: nginx:latest
    container_name: nginx_app
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db: